import { personalInfo } from './data';

export const siteConfig = {
  name: 'Kazi Shariful Islam | Full Stack Developer',
  author: 'Kazi Shariful Islam',
  title: 'Full Stack Developer | React, Next.js & Node.js Expert',
  headline: 'Full Stack Developer | React, Next.js, Node.js, NestJS, FastAPI',
  description: 'Full Stack Developer (React, Next.js, TypeScript, Node.js, Nest.js, FastAPI). Available for remote roles & consulting across EU, US, UK, AU, CA, Germany & Japan.',
  url: 'https://kazisharif.dev',
  ogImage: 'https://github.com/kazi331.png',
  twitterHandle: '@kazi331',
  email: 'kazisharif.dev@gmail.com',
  github: 'https://github.com/kazi331',
  linkedin: 'https://linkedin.com/in/kazi331',
  targetRegions: [
    'United States',
    'European Union',
    'United Kingdom',
    'Australia',
    'Canada',
    'Germany',
    'Japan',
  ],
  timeZones: ['EST', 'CST', 'PST', 'GMT', 'CET', 'AEST', 'JST'],
  keywords: [
    'Full Stack Developer for Hire',
    'React Developer',
    'Next.js Developer',
    'Node.js Developer',
    'TypeScript Expert',
    'NestJS Developer',
    'FastAPI Developer',
    'MERN Stack Developer',
    'Hire Remote React Developer',
    'Full Stack JavaScript Developer',
    'Next.js Consultant Available Now',
    'Node.js Express API Developer',
    'TypeScript React Developer for Hire',
    'Scalable FastAPI Backend Developer',
    'React Developer for Hire EU',
    'Full Stack Developer US Timezone',
    'Next.js Consultant UK',
    'Frontend React Developer Australia',
    'Node.js Developer Canada',
    'Full Stack MERN Stack Germany',
    'JavaScript Developer Japan Timezone',
    'Shopify App Developer',
    'Shopify Functions Specialist',
    'Kazi Shariful Islam',
  ],
};

export const jsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'WebSite',
      '@id': `${siteConfig.url}/#website`,
      url: siteConfig.url,
      name: siteConfig.name,
      description: siteConfig.description,
      publisher: {
        '@id': `${siteConfig.url}/#person`,
      },
      inLanguage: 'en-US',
    },
    {
      '@type': 'Person',
      '@id': `${siteConfig.url}/#person`,
      name: personalInfo.name,
      jobTitle: 'Senior Full Stack Developer & Systems Architect',
      url: siteConfig.url,
      email: personalInfo.email,
      image: personalInfo.profileImage,
      sameAs: [personalInfo.github, personalInfo.linkedin],
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Dhaka',
        addressCountry: 'BD',
      },
      hasOccupation: {
        '@type': 'Occupation',
        name: 'Full Stack Developer',
        occupationLocation: [
          {
            '@type': 'AdministrativeArea',
            name: 'Remote Worldwide (US, EU, UK, AU, CA, Germany, Japan)',
          },
        ],
        skills: [
          'React',
          'Next.js',
          'TypeScript',
          'JavaScript',
          'Node.js',
          'Express',
          'Nest.js',
          'FastAPI',
          'PostgreSQL',
          'GraphQL',
          'Shopify Functions',
        ],
      },
      knowsAbout: [
        'Full Stack Development',
        'Frontend Architecture',
        'Next.js App Router',
        'React Performance',
        'Node.js Microservices',
        'NestJS Dependency Injection',
        'FastAPI High-Concurrency APIs',
        'TypeScript Strict Typing',
        'PostgreSQL Database Optimization',
        'Shopify Functions & Apps',
        'Remote Engineering Collaboration',
      ],
      description: personalInfo.summary,
    },
    {
      '@type': 'ProfessionalService',
      '@id': `${siteConfig.url}/#service`,
      name: 'Kazi Shariful Islam — Full Stack Engineering & Consulting',
      url: siteConfig.url,
      priceRange: '$$$',
      areaServed: [
        'United States',
        'European Union',
        'United Kingdom',
        'Australia',
        'Canada',
        'Germany',
        'Japan',
        'Worldwide',
      ],
      availableLanguage: ['English', 'Bengali'],
      serviceType: [
        'Full Stack Web Development',
        'React & Next.js Consulting',
        'Node.js & NestJS API Engineering',
        'FastAPI Microservice Development',
        'Enterprise Web Application Architecture',
        'Shopify App & Storefront Optimization',
      ],
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Dhaka',
        addressCountry: 'BD',
      },
      aggregateRating: {
        '@type': 'AggregateRating',
        ratingValue: '5.0',
        reviewCount: '12',
        bestRating: '5',
        worstRating: '1',
      },
    },
  ],
};
