export const siteConfig = {
  name: 'Kazi Shariful Islam | Full Stack Developer',
  author: 'Kazi Shariful Islam',
  title: 'Full Stack Developer | React, Next.js & Node.js Expert',
  headline: 'Full Stack Developer | React, Next.js, Node.js, NestJS, FastAPI',
  description: 'Full Stack Developer (React, Next.js, TypeScript, Node.js, Nest.js, FastAPI). Available for remote roles & consulting across EU, US, UK, AU, CA, Germany & Japan.',
  url: 'https://kazisharif.dev',
  ogImage: 'https://github.com/kazi331.png',
  twitterHandle: '@kazi331',
  email: 'kazisharif.dev@gmail.com',
  github: 'https://github.com/kazi331',
  linkedin: 'https://linkedin.com/in/kazi331',
  targetRegions: [
    'United States',
    'European Union',
    'United Kingdom',
    'Australia',
    'Canada',
    'Germany',
    'Japan',
  ],
  timeZones: ['EST', 'CST', 'PST', 'GMT', 'CET', 'AEST', 'JST'],
  keywords: [
    'Full Stack Developer for Hire',
    'React Developer',
    'Next.js Developer',
    'Node.js Developer',
    'TypeScript Expert',
    'NestJS Developer',
    'FastAPI Developer',
    'MERN Stack Developer',
    'Hire Remote React Developer',
    'Full Stack JavaScript Developer',
    'Next.js Consultant Available Now',
    'Node.js Express API Developer',
    'TypeScript React Developer for Hire',
    'Scalable FastAPI Backend Developer',
    'React Developer for Hire EU',
    'Full Stack Developer US Timezone',
    'Next.js Consultant UK',
    'Frontend React Developer Australia',
    'Node.js Developer Canada',
    'Full Stack MERN Stack Germany',
    'JavaScript Developer Japan Timezone',
    'Shopify App Developer',
    'Shopify Functions Specialist',
    'Kazi Shariful Islam',
  ],
};
